name: Deploy desde github

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: deploy-dev
    steps:
    - name: serverless deploy
      uses: serverless/github-action@dev
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}